In [1]:

!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-08-17 01:37:54--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.06s   

2024-08-17 01:37:54 (18.8 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [60]:

with open('itenstboi.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [61]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  7590


In [62]:

print(text[:1000])

1up!: Grants an extra life.,
    3 Dollar Bill: Tears have random effects.,
    9 Volt: Quicker charge for item usage.,
    A Lump of Coal: Damage increases the further your tears travel.,
    A Quarter: Grants 25 coins.,
    Abaddon: Increases damage, removes red hearts, adds black hearts.,
    The Battery: Increases charge speed for items.,
    The Bean: Releases a toxic gas when used.,
    The Book of Belial: Increases damage for the current room.,
    The Book of Shadows: Grants temporary invincibility.,
    The D6: Allows re-rolling of item pedestals.,
    The D20: Rerolls all pickups into new pickups.,
    The D4: Rerolls all of Isaac's items.,
    The Guppy's Head: Releases flies when used.,
    The Halo: Increases all stats.,
    The Nail: Grants invincibility and boosts damage.,
    The Polaroid: Grants a shield when at half a heart or less.,
    The Pact: Increases damage and tears rate.,
    The Relic: Drops a soul heart every few rooms.,
    The Sacred Heart: Significantly 

In [63]:

chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size) #todos os caracteres presentes


 !',-.0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
70


In [64]:

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l]) # tokenização básica

print(encode("hii there"))
print(decode(encode("hii there")))
print(decode([46])) #a tokenização é realizada por letra aqui, diferente do card 22

[51, 52, 52, 1, 63, 51, 48, 61, 48]
hii there
c


In [65]:

import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # o dataset foi tokenizado e armazenado dentro de um tensor

torch.Size([7590]) torch.int64
tensor([ 8, 64, 59,  2, 17,  1, 24, 61, 44, 57, 63, 62,  1, 44, 57,  1, 48, 67,
        63, 61, 44,  1, 55, 52, 49, 48,  6,  4,  0,  1,  1,  1,  1, 10,  1, 21,
        58, 55, 55, 44, 61,  1, 19, 52, 55, 55, 17,  1, 37, 48, 44, 61, 62,  1,
        51, 44, 65, 48,  1, 61, 44, 57, 47, 58, 56,  1, 48, 49, 49, 48, 46, 63,
        62,  6,  4,  0,  1,  1,  1,  1, 16,  1, 39, 58, 55, 63, 17,  1, 34, 64,
        52, 46, 54, 48, 61,  1, 46, 51, 44, 61, 50, 48,  1, 49, 58, 61,  1, 52,
        63, 48, 56,  1, 64, 62, 44, 50, 48,  6,  4,  0,  1,  1,  1,  1, 18,  1,
        29, 64, 56, 59,  1, 58, 49,  1, 20, 58, 44, 55, 17,  1, 21, 44, 56, 44,
        50, 48,  1, 52, 57, 46, 61, 48, 44, 62, 48, 62,  1, 63, 51, 48,  1, 49,
        64, 61, 63, 51, 48, 61,  1, 68, 58, 64, 61,  1, 63, 48, 44, 61, 62,  1,
        63, 61, 44, 65, 48, 55,  6,  4,  0,  1,  1,  1,  1, 18,  1, 34, 64, 44,
        61, 63, 48, 61, 17,  1, 24, 61, 44, 57, 63, 62,  1,  9, 12,  1, 46, 58,
        5

In [66]:
n = int(0.9*len(data)) # efetuando train/test split
train_data = data[:n]
val_data = data[n:]

In [67]:
block_size = 8
train_data[:block_size+1]

tensor([ 8, 64, 59,  2, 17,  1, 24, 61, 44])

In [68]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}") #exemplifica o processo de treinamento para o modelo realizar predições do caractére seguinte

when input is tensor([8]) the target: 64
when input is tensor([ 8, 64]) the target: 59
when input is tensor([ 8, 64, 59]) the target: 2
when input is tensor([ 8, 64, 59,  2]) the target: 17
when input is tensor([ 8, 64, 59,  2, 17]) the target: 1
when input is tensor([ 8, 64, 59,  2, 17,  1]) the target: 24
when input is tensor([ 8, 64, 59,  2, 17,  1, 24]) the target: 61
when input is tensor([ 8, 64, 59,  2, 17,  1, 24, 61]) the target: 44


In [69]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):

    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 1,  1,  1, 20, 51, 44, 61, 56],
        [63, 51,  1, 56, 58, 61, 48,  1],
        [45, 44, 55, 55,  6,  4,  0,  1],
        [56, 44, 50, 48,  1, 58, 49,  1]])
targets:
torch.Size([4, 8])
tensor([[ 1,  1, 20, 51, 44, 61, 56, 48],
        [51,  1, 56, 58, 61, 48,  1, 47],
        [44, 55, 55,  6,  4,  0,  1,  1],
        [44, 50, 48,  1, 58, 49,  1, 63]])
----
when input is [1] the target: 1
when input is [1, 1] the target: 1
when input is [1, 1, 1] the target: 20
when input is [1, 1, 1, 20] the target: 51
when input is [1, 1, 1, 20, 51] the target: 44
when input is [1, 1, 1, 20, 51, 44] the target: 61
when input is [1, 1, 1, 20, 51, 44, 61] the target: 56
when input is [1, 1, 1, 20, 51, 44, 61, 56] the target: 48
when input is [63] the target: 51
when input is [63, 51] the target: 1
when input is [63, 51, 1] the target: 56
when input is [63, 51, 1, 56] the target: 58
when input is [63, 51, 1, 56, 58] the target: 61
when input is [63, 51, 1, 56, 58, 6

In [70]:
print(xb) # our input to the transformer

tensor([[ 1,  1,  1, 20, 51, 44, 61, 56],
        [63, 51,  1, 56, 58, 61, 48,  1],
        [45, 44, 55, 55,  6,  4,  0,  1],
        [56, 44, 50, 48,  1, 58, 49,  1]])


In [73]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):

        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 70])
tensor(4.8308, grad_fn=<NllLossBackward0>)

8YStBOyiPdh5AHbDbbczl
GF9A 3ql
KtS9,Mpf,BnVVXNaUUfCA4Th5gZSyY
ocmJ0fFzl3HUagEIX-oO,rrFIaHMMGIXItaRW3


In [72]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [74]:
batch_size = 32
for steps in range(3000):


    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.816384315490723


In [75]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


KySen.1WSQkVeSEGNTEXWXf!12ezmWcVxWP6lY'BfsV HKDCg'QGBiETcOWlrvBWrzy9-cuRNWlR23KW2 ItPpw-7ccbl7W-5JMwl-'zldGCG5cpjh!mgd-:XnnA4zK-t0AwxXkDtvmkedCqQczYjlWMPYJ1zg',TMogeTJ:xTbOM9-cS:x6jM2R6tySS:CYDIxHTh!W37RibhE74JQ35LqFueAyZn q,EjlOxRJ
jz VhK g'N,:8N sIt:7ObObFtxWXD97zlQynr'Y,cPbLdAMoWlzmetr87.6NPWl
T'g'YNf,WQNVVS1RLRpF,Qh4szv21m.mLNas98HiY
KU
NasT
rgBom8aIdR,9g69-7ldBfbvavXl,Gc3h1beE1bw38ngiRQ'98ZycLxHlP3UoAw9k!bNTMOa
qiYmfss475m6GcVG
E88YcK1gmW-x8FzXi,mwK
N aU9K1ko.:awD0YWle-RN97y0Y,6dVk9FAHLBX1z


In [36]:

torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [37]:


torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [38]:

xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev, 0)


In [39]:

wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

False

In [46]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [47]:

torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
wei =  q @ k.transpose(-2, -1)

tril = torch.tril(torch.ones(T, T))

wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [48]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [49]:
k.var()

tensor(1.0449)

In [50]:
q.var()

tensor(1.0700)

In [51]:
wei.var()

tensor(1.0918)

In [52]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [53]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [54]:
class LayerNorm1d:

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):

    xmean = x.mean(1, keepdim=True)
    xvar = x.var(1, keepdim=True)
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps)
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100)
x = module(x)
x.shape

torch.Size([32, 100])

In [55]:
x[:,0].mean(), x[:,0].std()

(tensor(0.1469), tensor(0.8803))

In [56]:
x[0,:].mean(), x[0,:].std()

(tensor(-9.5367e-09), tensor(1.0000))

In [57]:
import torch
import torch.nn as nn
from torch.nn import functional as F

batch_size = 16
block_size = 32
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(list(set(text)))
vocab_size = len(chars)

stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]


def get_batch(split):

    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2,-1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):

        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()

        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape


        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5059
step 300: train loss 2.4196, val loss 2.4338
step 400: train loss 2.3504, val loss 2.3566
step 500: train loss 2.2965, val loss 2.3129
step 600: train loss 2.2410, val loss 2.2500
step 700: train loss 2.2057, val loss 2.2191
step 800: train loss 2.1633, val loss 2.1864
step 900: train loss 2.1244, val loss 2.1510
step 1000: train loss 2.1038, val loss 2.1308
step 1100: train loss 2.0707, val loss 2.1197
step 1200: train loss 2.0377, val loss 2.0800
step 1300: train loss 2.0268, val loss 2.0650
step 1400: train loss 1.9918, val loss 2.0356
step 1500: train loss 1.9697, val loss 2.0293
step 1600: train loss 1.9645, val loss 2.0499
step 1700: train loss 1.9404, val loss 2.0129
step 1800: train loss 1.9095, val loss 1.9951
step 1900: train loss 1.9067, val loss 1.9855
step 2000: train loss 1.8854, val loss 1.9948
step 2100: train loss 1.