In [2]:
import torch

In [ ]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x.shape

torch.Size([2, 4])

In [ ]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [ ]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [ ]:
x.shape



torch.Size([2, 4])

In [ ]:
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()




torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [1]:
a = torch.ones(2,3)
print(f"pre squeeze {a.shape}")
squeezed = a.unsqueeze(2)
print(f"pos squeeze{squeezed.shape}")

NameError: name 'torch' is not defined

In [ ]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]]) # shape = (2,4)
y = torch.tensor([[1,2,3],
                  [2,3,4],
                  [4,5,6],
                  [7,8,9]]) # shape = (4,3)

In [ ]:
torch.matmul(x,y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [ ]:

x = torch.randn(1,4,5)
z = torch.cat([x,x], axis=1)
print('Concatenated axis 1:', x.shape, z.shape)


Concatenated axis 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [ ]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1)
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
