In [1]:
import torch

In [3]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x.shape

torch.Size([2, 4])

In [4]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [5]:
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [7]:
x.shape



torch.Size([2, 4])

In [8]:
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [11]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()




torch.Size([2, 1, 2, 1, 2])

In [12]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [13]:
a = torch.ones(2,3)
print(f"This is the shape before squeezing {a.shape}")
squeezed = a.unsqueeze(2)
print(f"This is the shape after squeezing {squeezed.shape}")

This is the shape before squeezing torch.Size([2, 3])
This is the shape after squeezing torch.Size([2, 3, 1])


In [15]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]]) # shape = (2,4)
y = torch.tensor([[1,2,3],
                  [2,3,4],
                  [4,5,6],
                  [7,8,9]]) # shape = (4,3)

In [16]:
torch.matmul(x,y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [17]:

x = torch.randn(1,4,5)
z = torch.cat([x,x], axis=1)
print('Concatenated axis 1:', x.shape, z.shape)
# z tensor has shape (1,8,5)

Concatenated axis 1: torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [20]:
x = torch.randn(3,20,10)
z = x.permute(2,0,1)
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
